spring:
  datasource:
    url: jdbc:mysql://localhost/algafood?serverTimezone=UTC
    username: root
    password: thomaz@0806
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect